{"uuid": "baad514b-8472-49eb-ab0d-efdca9fa30ca", "children": ["7daf3885-3649-491a-8e1c-8bc6ba4d2a73"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom no such execution context: loader has changed while resolving nodes\n  (Session info: chrome=115.0.5790.99)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x0037A813+48355]\n\t(No symbol) [0x0030C4B1]\n\t(No symbol) [0x00215358]\n\t(No symbol) [0x00217D86]\n\t(No symbol) [0x002199E1]\n\t(No symbol) [0x00219A80]\n\t(No symbol) [0x00261F1B]\n\t(No symbol) [0x0026093C]\n\t(No symbol) [0x0025A536]\n\t(No symbol) [0x002382DC]\n\t(No symbol) [0x002393DD]\n\tGetHandleVerifier [0x005DAABD+2539405]\n\tGetHandleVerifier [0x0061A78F+2800735]\n\tGetHandleVerifier [0x0061456C+2775612]\n\tGetHandleVerifier [0x004051E0+616112]\n\t(No symbol) [0x00315F8C]\n\t(No symbol) [0x00312328]\n\t(No symbol) [0x0031240B]\n\t(No symbol) [0x00304FF7]\n\tBaseThreadInitThunk [0x76BA00C9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77477B1E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77477AEE+238]\n\n", "trace": "  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Credence Class Notes\\CredenceBatches\\CredenceBatch#14 & 15\\CredKart_Pytest_Project\\testCases\\conftest.py\", line 21, in setup\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 49, in __init__\n    super().__init__(\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 54, in __init__\n    super().__init__(\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 206, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\HP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1690943036818, "stop": 1690943047051}], "start": 1690943036818, "stop": 1690943047338}